config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root 'home#index'

  get '/register' => 'users#new'
  get 'home/hit' => 'home#hit'
  get 'home/stay' => 'home#stay'
  get 'home/index' => 'home#index'
  get '/login' => 'sessions#new'
  get '/users/leaderboard' => 'users#leaderboard'
  get '/users/online' => 'users#online'
  get '/poker' => 'poker#show'
  get '/flop' => 'poker#flop'
  get '/new-game' => 'poker#create'
  get '/search' => 'search#index'
  get '/friends' => 'friends#index'
  get '/friends/destroy'
  get '/pvt-msg' => 'private_messages#index'
  get '/new-pvt-msg' => 'private_messages#new'

  post '/register' => 'users#create'
  post '/login' => 'sessions#create'
  post '/game-invite' => 'invitation#transmit'
  post 'home/wager' => 'home#wager'
  post '/friends/request' => 'friends#request'
  post '/accept-req' => 'friend_requests#accept'
  post '/bet' => 'poker#bet'
  post '/call' => 'poker#call'

  delete '/logout' => 'sessions#destroy'

  resources :friend_requests
  resources :messages
  resources :users do
    member do
      get :confirm_email
    end
  end

  mount ActionCable.server, at: '/cable'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    friendships = Friendship.where(user_id: current_user.id)
    @friends = friendships.map { |f| User.find(f.friend_user_id) }
    @incoming = FriendRequest.where(requested_id: current_user)
    # @incoming = incoming.map { |u| User.find(u.sender_id) }
  end  

  # def send_friend_request
  #   FriendRequest.create(sender_id: current_user.id)
  # end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_index.html.erb
<%= render 'friend_requests/index' %>

<% if @friends %>
  <% @friends.each do |friend| %>
    <div id="friend"><span id="friend-username"><%= friend.username %></span>
      <% if friend.online %>
        <span id="friend-online"> is online! </span>
        <%= link_to game_invite_path(friend_id: User.find(friend.id)), remote: true, method: :post do %>
          <button>Play Me</button>
        <% end %>
      <% end %>
        <%= link_to root_path, remote: true, method: :get do %>
          <button>Message</button>
        <% end %>
    </div>
  <% end %>
<% end %>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/index.js.erb
$('.friends-list').html("<%= j (render 'index')%>");
$('.friends-list').fadeIn();