config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root 'home#index'

  get '/register' => 'users#new'
  get 'home/hit' => 'home#hit'
  get 'home/stay' => 'home#stay'
  get 'home/index' => 'home#index'
  get '/login' => 'sessions#new'
  get '/users/leaderboard' => 'users#leaderboard'
  get '/users/online' => 'users#online'
  get '/poker' => 'poker#show'
  get '/flop' => 'poker#flop'
  get '/new-game' => 'poker#create'
  get '/search' => 'search#index'
  get '/friends' => 'friends#index'
  get '/friends/destroy'
  get '/pvt-msg' => 'private_messages#index'
  get '/new-pvt-msg' => 'private_messages#new'

  post '/register' => 'users#create'
  post '/login' => 'sessions#create'
  post '/game-invite' => 'invitation#transmit'
  post 'home/wager' => 'home#wager'
  post '/friends/request' => 'friends#request'
  post '/accept-req' => 'friend_requests#accept'
  post '/bet' => 'poker#bet'
  post '/call' => 'poker#call'

  delete '/logout' => 'sessions#destroy'

  resources :friend_requests
  resources :messages
  resources :users do
    member do
      get :confirm_email
    end
  end

  mount ActionCable.server, at: '/cable'
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_logged-in.html.erb
<ul>
  <% if logged_in? %>
    <li>Logged in as: <span id="current_user"><%= current_user.username %></span></li>
    <li>Current balance: <span id="balance"><%= current_user.balance %></span></li>
  <% end %>
    <li><%= Time.now.strftime("%m/%d/%Y %I:%M%p") %></li>
</ul>

app/views/shared/_nav.html.erb
<div class="navbar navbar-inverse navbar-twitch" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span class="small-nav"> <span class="logo"> <B> </span> </span>
        <span class="full-nav"> < Bootsnipp > </span>
      </a>
    </div>
    <div class="">
      <ul class="nav navbar-nav">
        <li class="active">
          <a href="#">
            <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Home"> 
            <i class="fas fa-home"></i>
            </span>
            <span class="full-nav">Home</span>
          </a>
        </li>
         <li>
          <a href="#btc">
            <span class="small-nav" data-toggle="tooltip" data-placement="right" title="My BTC"> 
            <i class="fab fa-btc" id="btc"></i> 
            </span>
            <span class="full-nav">My Bitcoin</span>
          </a>
        </li>
        <li>
          <a href="#poker">
            <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Poker"> 
              <span id="spade">♠</span>
            </span>
            <span class="full-nav">Hold Em Poker</span>
            <div class="poker-invite">
               <%= render 'invitation/transmit' %>
            </div>
          </a>
        </li>
        <li>
          <a href="#blackjack">
            <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Blackjack"> 
              <span id="twenty-one">21</span>
            </span>
            <span class="full-nav">Blackjack</span>
          </a>
        </li>
        <li>
          <%= link_to friends_path, remote: true, method: :get do %>
              <span class="small-nav" data-toggle="tooltip" data-placement="right" title="My Friends"> 
                <i class="fas fa-users"></i>
              </span>
              <span class="full-nav">My Friends</span>
       <!--    </a> -->
              <div class="friends-list">
              </div>
          <% end %>
        </li>
        <li>
          <%= link_to pvt_msg_path, remote: true, method: :get do %>
            <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Private Message"> 
              <i class="far fa-comments"></i>
            </span>
            <span class="full-nav">Private Chat</span>
            <div class="chat-area">
            </div>
            <div class="new-pvt-msg">
              <%= render 'private_messages/new' %>
            </div>     
          <% end %>  
        </li>
        <li id ="mag-glass">
          <a href="#search">
            <span class="small-nav" data-toggle="tooltip" data-placement="right" title="Search Users"> 
              <i class="fas fa-search"></i>
            <span class="full-nav">Search Users</span>
          </a>
          <div class="user-search">
            <%= form_tag(search_path, :method => "get", id: "search-form", remote:true) do %>
              <%= text_field_tag :username, params[:username], placeholder: "Find A User", :id => "search-field" %>
              <div class="search-results">
              </div>
          <% end %>
          </div>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container">
  <div class="row">
    <h2>Bootstrap Navigation meets Twitch Navigation</h2>
        <p>This is just a quick and dirty example I made to show off to a friend. Don't forget to change the theme using the dropdown above.</p>
  </div>
    <div class="row">
        <h2>Navbar Styles</h2>
        <p>Just to show off how easy it is to theme!</p>
        <button type="button" class="btn btn-inverse nav-style-toggle disabled" data-type="inverse"> Inverse</button>
        <button type="button" class="btn btn-default nav-style-toggle" data-type="default"> Default</button>
        <button type="button" class="btn btn-purple nav-style-toggle" data-type="purple"> Purple</button>
    </div>
</div>