config/routes.rb
Rails.application.routes.draw do
  get 'search/index'

  root 'home#index'

  get '/register' => 'users#new'
  get 'home/hit' => 'home#hit'
  get 'home/stay' => 'home#stay'
  get 'home/index' => 'home#index'
  get '/login' => 'sessions#new'
  get '/users/leaderboard' => 'users#leaderboard'
  get '/users/online' => 'users#online'
  get '/poker' => 'poker#show'
  get '/flop' => 'poker#flop'
  get '/new-game' => 'poker#create'
  get '/search' => 'search#index'
  get '/friends' => 'friends#index'
  get '/friends/destroy'
  get '/pvt-msg' => 'private_messages#index'
  get '/new-pvt-msg' => 'private_messages#new'

  post '/register' => 'users#create'
  post '/login' => 'sessions#create'
  post '/game-invite' => 'invitation#transmit'
  post 'home/wager' => 'home#wager'
  post '/friends/request' => 'friends#request'
  post '/accept-req' => 'friend_requests#accept'
  post '/bet' => 'poker#bet'
  post '/call' => 'poker#call'

  delete '/logout' => 'sessions#destroy'

  resources :friend_requests
  resources :messages
  resources :users do
    member do
      get :confirm_email
    end
  end

  mount ActionCable.server, at: '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :js

  def index
    @incoming = FriendRequest.where(requested_id: current_user)
    $game = Game.new
    $wager = 1
    display_hands
  end

  def hit
    $card = nil
    $game.human_hits
    @card = $game.human_last_card
    if $game.human_busts?
      $card = $game.human_last_card
      evaluate
      render :evaluate and return
    end
  end 

  def stay
    evaluate
  end

  def evaluate
    $game.dealer_turn
    @cards = $game.dealer_last_cards
    @winner = $game.find_winner
    display_hands 
    change_balance
    $game.reset
  end

  def wager
    $wager ||= 1
    $wager += params[:wager].to_i
  end

  def change_balance
    if user_won?
      new_balance = current_balance + $wager
      current_user.update!(balance: new_balance)
    elsif dealer_won?
      new_balance = current_balance - $wager
      current_user.update!(balance: new_balance)
    end
  end

  private

  def current_balance
    current_user.balance
  end

  def user_won?
    $game.winner == 'human'
  end

  def dealer_won?
    $game.winner == 'dealer'
  end

  def display_hands
    @human_hand = $game.human_hand
    @dealer_hand = $game.dealer_hand
  end
end 

class BlackjackGame
  attr_accessor :human, :dealer
  attr_reader :winner

  def initialize
    $human = BlackjackPlayer.new('You')
    $dealer = BlackjackPlayer.new('Dealer')
    @winner = nil
  end

  def human_hits
    $human.deal_one
    $human.set_hand_value
  end

  def human_hand
    $human.hand
  end 

  def human_last_card
    human_hand.last
  end

  def dealer_last_cards
    dealer_hand[1..-1]
  end

  def dealer_hand
    $dealer.hand
  end

  def dealer_hits
    $dealer.deal_one
  end

  def human_busts?
    $human.hand_value > 21
  end

  def dealer_busts?
    $dealer.hand_value > 21
  end

  def anyone_bust?
    human_bust? || dealer_busts?
  end

  def dealer_turn
    until $dealer.hand_value >= 17
      dealer_hits
      $dealer.set_hand_value
    end
  end

  def reset
    $human.hand = []
    $dealer.hand = []
  end 

  def find_winner
    if $human.hand_value == $dealer.hand_value
      @winner = nil
      "It's a draw!"
    elsif dealer_busts? && human_busts?
      @winner = nil
      "Both bust! Draw!"
    elsif dealer_busts? && !human_busts?
      @winner = 'human'
      ($human.hand_value == 21) ? "BLACKJACK! You win!" : "Dealer busts! You win!"
    elsif human_busts? && !dealer_busts?
      @winner = 'dealer'
      ($dealer.hand_value == 21) ? "Dealer wins with BLACKJACK!" : "You bust! Dealer wins!"
    elsif $human.hand_value > $dealer.hand_value
      @winner = 'human'
      "You win!"
    else
      @winner = 'dealer'
      "Dealer wins!"
    end
  end

  def user_won?

  end
end

class BlackjackPlayer
  attr_accessor :hand, :hand_value
  attr_reader :name

  def initialize(name)
    @name = name
    @hand = [random_card, random_card]
    @hand_value = 0
    set_hand_value
  end

  def deal_one
    @hand << random_card
  end

  def has_ace?
    !hand.select { |card| card.rank == 'A' }.nil?
  end

  def ace_count
    hand.select { |card| card.rank == 'A' }.size
  end

  def busted?
    self.hand_value > 21
  end

  def set_hand_value
    self.hand_value = 0
    self.hand.each { |card| self.hand_value += card.value }
    ace_count.times { self.hand_value -= 10 } if busted? && has_ace?
  end

  private

  def random_card
    idx = rand(52) + 1
    Card.find(idx)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_evaluate.js.erb
$('#message').append("<%= @winner %>");
<% if !$card.nil? %>
  $('.player-hand').append("<%= j (image_tag $card.avatar_file_name) %>");
<% end %>
<% if !@cards.nil? %>
  <% @cards.each do |card| %>
    $('.dealer-hand').append("<%= j (image_tag card.avatar_file_name) %>");
  <% end %>
<% end %>
$('.play-again').css('visibility', 'visible');
$('#hit').css('visibility', 'hidden');
$('#stay').css('visibility', 'hidden');

app/views/home/_footer.html.erb
<div class="footer-wrap">
  <div class="button-area-left">
      <%= link_to home_hit_path, remote:true, id: 'hit', method: :get do %>
        <button>Hit</button>
      <% end %>
      <%= link_to home_stay_path, remote:true, id: 'stay', method: :get do %>
        <button>Stay</button>
      <% end %>
      <div class="play-again">
        <%= link_to home_index_path, remote: true, method: :get do %>
          <button>Play Again</button>
        <% end %>
      </div>
  </div>
  <div class="wager-buttons">
    <%= button_to "1", home_wager_path, name: 'wager', value: 1, remote: true %>
    <%= button_to "5", home_wager_path, name: 'wager', value: 5, remote: true %>
    <%= button_to "20", home_wager_path, name: 'wager', value: 20, remote: true %>
    <%= button_to "50", home_wager_path, name: 'wager', value: 50, remote: true %>
    <%= button_to "100", home_wager_path, name: 'wager', value: 100, remote: true %>
    <%= button_to "250", home_wager_path, name: 'wager', value: 250, remote: true %>
    <%= button_to "500", home_wager_path, name: 'wager', value: 500, remote: true %>
    <%= button_to "1000", home_wager_path, name: 'wager', value: 1000, remote: true %>
  </div>
  <div class="result">
    <p id="wager">Current Wager: <span id="current-wager"><%= $wager %></span></p>
    <h2 id="message">
      <span id="flash-msg"><%= flash[:success] %></span>
    </h2>
  </div>
</div>

app/views/home/_index.html.erb
<%= render 'shared/nav' %>

<%= render 'play-area' %>

app/views/home/_play-area.html.erb
  <div class="body-wrap">
    <div class="username">
      <h2>Your Hand</h2>
    </div>
    <div class="play-area">
      <div class="player">
        <%= render 'player-hand' %>
      </div>
    </div>
    <div class="username">
      <h2>Dealer Hand</h2>
    </div>
    <div class="play-area">
      <div class="player">
        <div class="dealer-hand">
          <%= image_tag @dealer_hand.first.avatar_file_name %>
        </div>
      </div>
    </div>
  </div>

  <%= render 'footer' %>

app/views/home/_player-hand.html.erb
<div class="player-hand">
  <% @human_hand.each do |card| %>
    <%= image_tag card.avatar_file_name %>
  <% end %>
</div>

app/views/home/hit.js.erb
$('.player-hand').append("<%= j (image_tag @card.avatar_file_name) %>");

app/views/home/index.html.erb
<!-- <div class="overlay">
  <div class="message">
    <h1 id="play">♠ ♥ Let's Play Blackjack! ♣ ♦</h1>
  </div>
</div>
 -->
<% if !logged_in? %>
  <div class= "overlay">
    <div class="overlay-txt">
      You must be logged in to play.
    </div>
  </div>
<% end %>

<%= render 'shared/nav' %>
<%= render 'play-area' %>

app/views/home/index.js.erb
$('body').html("<%= j (render 'index') %>");
$('.play-again').css('visibility', 'hidden');

app/views/home/stay.js.erb
$('#message').append("<%= @winner %>");
<% if !@cards.nil? %>
  <% @cards.each do |card| %>
    $('.dealer-hand').append("<%= j (image_tag card.avatar_file_name) %>");
  <% end %>
<% end %>
$('.play-again').css('visibility', 'visible');
$('#hit').css('visibility', 'hidden');
$('#stay').css('visibility', 'hidden');

app/views/home/untitled.js.erb
$('#message').append("<%= @winner %>");
<% if !$card.nil? %>
  $('.player-hand').append("<%= j (image_tag $card.avatar_file_name) %>");
<% end %>
<% if !@cards.nil? %>
  <% @cards.each do |card| %>
    $('.dealer-hand').append("<%= j (image_tag card.avatar_file_name) %>");
  <% end %>
<% end %>
$('.play-again').css('visibility', 'visible');
$('#hit').css('visibility', 'hidden');
$('#stay').css('visibility', 'hidden');

app/views/home/wager.js.erb
$('#current-wager').text("<%= $wager %>");